language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

services:
  - docker

install:
  - mvn clean install -DskipTests

script:
  - mvn test
  - docker rm $(docker ps -a -q)
  - docker build client -t jbtvjyc:client
  - cd server
  - docker run -d --name client_test -p 8081:8081 jbtvjyc:client
  - mvn failsafe:integration-test -Dit.test=com.jbtvjyc.scrabble.data.MoteurWebControlleurITCase#demanderAuJoueurDeJouerTest
  - docker start client_test
  - mvn failsafe:integration-test -Dit.test=com.jbtvjyc.scrabble.data.MoteurWebControlleurITCase#demanderAuJoueurDeJouerTest2foisDeSuite
  - mvn exec:java &
  - cd ../client
  - mvn exec:java