language: java

jdk:
  - openjdk11

services:
  - docker

install:
  - mvn clean install -DskipTests

before_script:
  - docker ps -a -q
  - docker build server -t jbtvjyc:server
  - docker build client -t jbtvjyc:client
  - docker images

script:
  #- mvn test
  #- cd server
  #- mvn exec:java &
  #- cd ../client
  #- mvn exec:java
  - mvn test
  - docker-compose up --scale client=3
  - docker rm $(docker ps -a -q)
  - docker ps -a -q
  - docker rmi jbtvjyc:server
  - docker rmi jbtvjyc:client

#script:
 # - mvn test
