version: '3'

services:

  serveur:
    image: jbtvjyc:server
    container_name: server
    networks:
      testing_net:
        ipv4_address: 172.28.0.253
    depends_on:
      - client
    ports:
      - "8080:8080"

  client:
    image: jbtvjyc:client
    container_name: client
    environment:
      - PORT=8081
      - NOM=Mopolo le Roi des Mots
      - AUTOCONNECT=autoconnect
      - SERVERIP=172.28.0.253
      - OWNIP=172.28.0.3
    networks:
      testing_net:
        ipv4_address: 172.28.0.3
    ports:
      - "8081:8081"

  client2:
    image: jbtvjyc:client
    container_name: client2
    environment:
      - PORT=8082
      - NOM=Menez la Falaise
      - AUTOCONNECT=autoconnect
      - SERVERIP=172.28.0.253
      - OWNIP=172.28.0.4
    networks:
      testing_net:
        ipv4_address: 172.28.0.4
    ports:
      - "8082:8082"

  client3:
    image: jbtvjyc:client
    container_name: client3
    environment:
      - PORT=8083
      - NOM=Renevier le Pionnier
      - AUTOCONNECT=autoconnect
      - SERVERIP=172.28.0.253
      - OWNIP=172.28.0.5
    networks:
      testing_net:
        ipv4_address: 172.28.0.5
    ports:
      - "8083:8083"

  client4:
    image: jbtvjyc:client
    container_name: client4
    environment:
      - PORT=8084
      - NOM=Arnault le plus beau
      - AUTOCONNECT=autoconnect
      - SERVERIP=172.28.0.253
      - OWNIP=172.28.0.6
    networks:
      testing_net:
        ipv4_address: 172.28.0.6
    ports:
      - "8084:8084"




networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16